from __future__ import annotations


DEFAULT_AGENT_SOURCE_CATALOG: list[dict[str, object]] = [
    {
        "name": "小林面试笔记 Agent 专题 - 什么是 Agent",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/1_whatisagent.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/1_whatisagent.html", "category_hint": "AI Agent 概念与架构", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 核心组件",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/2_components.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/2_components.html", "category_hint": "AI Agent 概念与架构", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - Workflow 与 Tools",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/3_workflow_tools.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/3_workflow_tools.html", "category_hint": "AI Agent 概念与架构", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 设计范式",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/4_patterns.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/4_patterns.html", "category_hint": "AI Agent 设计范式", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - ReAct",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/5_react.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/5_react.html", "category_hint": "AI Agent 设计范式", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 三种范式",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/6_three_patterns.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/6_three_patterns.html", "category_hint": "AI Agent 设计范式", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 任务拆分",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/7_tasksplit.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/7_tasksplit.html", "category_hint": "AI Agent 工程实践", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 记忆机制",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/8_memory.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/8_memory.html", "category_hint": "AI Agent 记忆机制", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 记忆存储",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/9_memory_storage.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/9_memory_storage.html", "category_hint": "AI Agent 记忆机制", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - Multi-Agent",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/10_multiagent.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/10_multiagent.html", "category_hint": "AI Agent 多智能体", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - Single 与 Multi",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/11_single_multi.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/11_single_multi.html", "category_hint": "AI Agent 多智能体", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 记忆压缩",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/12_memcompress.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/12_memcompress.html", "category_hint": "AI Agent 记忆机制", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 规划能力",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/14_planning.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/14_planning.html", "category_hint": "AI Agent 规划能力", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 反思机制",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/15_reflection.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/15_reflection.html", "category_hint": "AI Agent 反思机制", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Agent 专题 - 协作机制",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/agent/16_collab.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/agent/16_collab.html", "category_hint": "AI Agent 多智能体", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Tools - Function Calling",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/tools/1_function_calling.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/tools/1_function_calling.html", "category_hint": "LLM 工具调用", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Tools - Function Calling 训练",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/tools/3_fc_training.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/tools/3_fc_training.html", "category_hint": "LLM 工具调用", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Tools - Skills",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/tools/13_skill.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/tools/13_skill.html", "category_hint": "Agent Skills 与任务路由", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "小林面试笔记 Tools - FC Skill MCP",
        "source_type": "web",
        "base_url": "https://xiaolinnote.com/ai/tools/15_fc_skill_mcp.html",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://xiaolinnote.com/ai/tools/15_fc_skill_mcp.html", "category_hint": "MCP 与 Agent 工具生态", "max_questions": 2, "use_firecrawl": False},
    },
    {
        "name": "Datawhale hello-agents README",
        "source_type": "github",
        "base_url": "https://raw.githubusercontent.com/datawhalechina/hello-agents/main/README.md",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://raw.githubusercontent.com/datawhalechina/hello-agents/main/README.md", "category_hint": "AI Agent 工程实践", "max_questions": 4, "use_firecrawl": False},
    },
    {
        "name": "AgentGuide README",
        "source_type": "github",
        "base_url": "https://raw.githubusercontent.com/adongwanai/AgentGuide/main/README.md",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://raw.githubusercontent.com/adongwanai/AgentGuide/main/README.md", "category_hint": "AI Agent 工程实践", "max_questions": 4, "use_firecrawl": False},
    },
    {
        "name": "AIGC Interview Book README",
        "source_type": "github",
        "base_url": "https://raw.githubusercontent.com/WeThinkIn/AIGC-Interview-Book/main/README.md",
        "language": "zh-CN",
        "crawl_strategy": "http",
        "config": {"request_url": "https://raw.githubusercontent.com/WeThinkIn/AIGC-Interview-Book/main/README.md", "category_hint": "AI Agent 与大模型面试", "max_questions": 4, "use_firecrawl": False},
    },
]
